# Generated by Django 5.1.6 on 2025-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
